#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# 30-kind-up.sh — create the Kind cluster that hosts kagent.
#
# Renders kind/cluster.yaml from .env (so the A2A NodePort is configurable),
# then creates the cluster if it does not already exist. Idempotent.
# ---------------------------------------------------------------------------
set -euo pipefail
. "$(dirname "$0")/lib.sh"
ensure_env_file
load_env

require_cmd kind
require_cmd kubectl

CLUSTER="${KIND_CLUSTER_NAME:-kagent-copilot}"
NODEPORT="${KAGENT_A2A_NODEPORT:-30883}"
CFG="$REPO_ROOT/kind/cluster.yaml"

# --- render cluster config (always, to keep it in sync with .env) ---------
mkdir -p "$REPO_ROOT/kind"
cat > "$CFG" <<EOF
# Generated by 30-kind-up.sh from .env — safe to regenerate.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ${CLUSTER}
nodes:
  - role: control-plane
    extraPortMappings:
      # Publish the kagent controller A2A NodePort to the host so a dev tunnel
      # can expose it to Microsoft Copilot Studio.
      - containerPort: ${NODEPORT}
        hostPort: ${NODEPORT}
        protocol: TCP
EOF
ok "rendered ${CFG} (A2A nodePort ${NODEPORT})"

# --- create cluster if absent --------------------------------------------
if kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
  ok "Kind cluster '${CLUSTER}' already exists — skipping create"
else
  log "creating Kind cluster '${CLUSTER}'..."
  kind create cluster --config "$CFG" --wait 120s
  ok "Kind cluster '${CLUSTER}' created"
fi

# --- ensure kubectl context + readiness ----------------------------------
kubectl cluster-info --context "kind-${CLUSTER}" >/dev/null 2>&1 \
  || die "kubectl cannot reach cluster context kind-${CLUSTER}"
wait_for "node Ready" 120 bash -c \
  "kubectl --context kind-${CLUSTER} get nodes --no-headers 2>/dev/null | grep -qw Ready"

kubectl --context "kind-${CLUSTER}" get nodes
ok "kind-up complete"
